[metadata]
name = napari-autofill-contours
version = 0.1.0
author = You
description = Auto-fill all closed contours in an RGB image as labels
license = MIT

[options]
packages = find:
install_requires =
    numpy
    scikit-image
    magicgui
    napari

[options.entry_points]
napari.manifest =
    napari-autofill-contours = napari_autofill_contours:napari.yaml
